// Content registry for the "What is this AI feature?" info popups.
// One entry per AI feature in the product (45). Each explains, for a
// non-technical buyer: WHAT it does, HOW it works behind the scenes, WHY it is
// valuable, and the PROBLEM it solves — plus which of the three Progress layers
// it uses (Agentic RAG · MCP Server · Retrieval Agent/RAO · Visual LLM).
//
// Surfaced everywhere an AI feature appears via the <AiInfo id="..."/> button.

export type AiLayer =
  | "Agentic RAG"
  | "MCP Server"
  | "Retrieval Agent (RAO)"
  | "Visual LLM"
  | "Human-in-the-loop";

export interface AiFeatureInfo {
  id: string;
  name: string;
  /** One-line tagline shown under the title. */
  tagline: string;
  layers: AiLayer[];
  /** REST route behind it (also the auto-generated MCP tool). */
  route: string;
  what: string;
  how: string;
  why: string;
  problem: string;
}

const F = (e: AiFeatureInfo) => e;

export const AI_FEATURES: Record<string, AiFeatureInfo> = {
  "ops-assistant": F({
    id: "ops-assistant",
    name: "Ops Assistant",
    tagline: "Ask anything about your live operation, in plain English.",
    layers: ["Retrieval Agent (RAO)", "MCP Server", "Agentic RAG"],
    route: "POST /api/ai/ops-assistant",
    what: "A conversational agent that answers free-text questions about the live business — open jobs, overdue invoices, technician load, stock, SLA risk — and shows its working as it goes.",
    how: "The Retrieval Agent Orchestrator (RAO) decomposes your question into sub-queries, then calls the live ERP through the MaintenanceOS MCP Server (the same 80+ tools an external agent could use) and the knowledge base via Agentic RAG. It correlates the results and writes a grounded answer. You watch each real step stream in — the plan, every live query it runs, then the answer.",
    why: "It turns a question that used to mean opening five screens and exporting to a spreadsheet into a 30-second conversation. Anyone — not just a report-writer — can interrogate the business.",
    problem: "The answer you need is almost never in one place; it is split across jobs, invoices, people and stock. People spend the majority of their time gathering and correlating data instead of acting on it.",
  }),
  "knowledge-copilot": F({
    id: "knowledge-copilot",
    name: "Knowledge Copilot",
    tagline: "Cited answers from your policies, manuals and SOPs.",
    layers: ["Agentic RAG"],
    route: "POST /api/ai/ask",
    what: "Grounded question-answering over your document knowledge base — safety policies, equipment manuals, finance policy, the user guide and ingested ERP records — with a citation for every claim.",
    how: "Progress Agentic RAG runs semantic vector search to find the most relevant passages even when the words don't match exactly, then generates an answer strictly from those passages and returns the sources. Below a confidence threshold it says 'not enough data' rather than guessing.",
    why: "Staff get a trustworthy, verifiable answer in seconds instead of hunting through PDFs — and every answer can be checked against its source.",
    problem: "Critical knowledge is locked in documents nobody has time to read. Generic chatbots either can't see those documents or invent answers that can't be trusted.",
  }),
  "help-assistant": F({
    id: "help-assistant",
    name: "Help Assistant",
    tagline: "An in-app guide that actually knows this product.",
    layers: ["Agentic RAG"],
    route: "POST /api/ai/ask (scoped to the user guide)",
    what: "The bottom-right help bubble — a chatbot that answers 'how do I…' questions about MaintenanceOS itself, grounded in the full user guide.",
    how: "Same Agentic RAG engine as the Knowledge Copilot, but retrieval is filtered to the 'userguide' document set, so answers stay on-product and cite the relevant section of the guide.",
    why: "New users self-serve instead of raising support tickets or interrupting a colleague — onboarding and adoption speed up.",
    problem: "Manuals go unread and 'how do I do X' questions create a constant support drag. Static help pages can't answer a specific question in context.",
  }),
  "semantic-search": F({
    id: "semantic-search",
    name: "Semantic Search",
    tagline: "Find related records and documents by meaning, not keywords.",
    layers: ["Agentic RAG"],
    route: "POST /api/ai/find",
    what: "Vector + keyword search across the knowledge base that returns the most relevant records and document passages, powering 'related items' panels and lookups.",
    how: "Agentic RAG embeds your query and matches it against the indexed corpus by semantic similarity, so 'water coming through the ceiling' finds 'roof leak' jobs even with no shared words.",
    why: "People find the right precedent or document on the first try, without knowing the exact term or reference number.",
    problem: "Keyword search misses anything phrased differently, and the right past job or document is invisible if you don't already know what it's called.",
  }),
  "retrieval-agent": F({
    id: "retrieval-agent",
    name: "Retrieval Agent",
    tagline: "Multi-source orchestration over live data + documents.",
    layers: ["Retrieval Agent (RAO)", "MCP Server", "Agentic RAG"],
    route: "POST /api/ai/agent",
    what: "The non-streaming orchestration endpoint behind agentic answers: plans a question, queries multiple sources, and synthesises one cited response.",
    how: "The RAO plans which ERP tables (via MCP) and which documents (via RAG) to consult, runs them in parallel where possible, correlates the results, and returns a single answer. It inherits the caller's permissions, so it only ever sees what that user is allowed to see.",
    why: "It is the reusable engine that makes every agentic feature possible — and proves the architecture works against your real systems.",
    problem: "No single tool joins live transactional data with the rules and context buried in documents; a human has to do that synthesis by hand, every time.",
  }),
  briefing: F({
    id: "briefing",
    name: "Daily Operations Briefing",
    tagline: "Your morning read: what needs attention, ranked.",
    layers: ["Agentic RAG", "MCP Server"],
    route: "GET /api/ai/briefing",
    what: "A board-style daily brief that opens on the real pressure points — SLA breaches, unassigned urgent jobs, overdue invoices and low stock — in priority order.",
    how: "The server computes exact KPIs from the database, then ARAG narrates them into a concise, human brief. The figures are real; the narration just makes them readable and prioritised.",
    why: "A manager starts the day knowing the three things that matter instead of scanning dashboards to figure it out.",
    problem: "Dashboards show everything and prioritise nothing. The important signal is buried among dozens of tiles.",
  }),
  "dispatch-actions": F({
    id: "dispatch-actions",
    name: "Dispatch Next-Best-Actions",
    tagline: "Ranked assign / escalate / reschedule moves, one click to apply.",
    layers: ["MCP Server", "Agentic RAG", "Human-in-the-loop"],
    route: "POST /api/ai/dispatch-actions",
    what: "Looks at the unassigned and at-risk queue and proposes the best next move for each job — who to assign, what to escalate, what to reschedule — ranked by urgency and SLA.",
    how: "It reads open jobs, technician skills, territories and availability from the live ERP, matches required skills to available people, and ranks by priority and SLA pressure. Each proposal is applied with one click and recorded in the audit log.",
    why: "Dispatchers act on a prioritised shortlist instead of mentally juggling the whole board, and nothing slips because a skill didn't match.",
    problem: "Manual dispatch relies on one person holding the whole board in their head; under load, the wrong tech gets sent or urgent jobs are missed.",
  }),
  "day-plan": F({
    id: "day-plan",
    name: "Technician Day-Plan",
    tagline: "A narrated run-order with clash detection.",
    layers: ["MCP Server", "Agentic RAG"],
    route: "POST /api/ai/day-plan",
    what: "Builds a clear running order for a technician's day and flags scheduling clashes and wasteful back-and-forth travel.",
    how: "It pulls the technician's scheduled jobs for the day, deterministically detects overlaps, then has ARAG narrate the plan with start/finish times and warnings.",
    why: "Technicians and coordinators see the day at a glance and catch double-bookings before they cost a wasted trip.",
    problem: "Schedules are a list, not a plan — clashes and inefficient routing are only discovered when a tech is already on the road.",
  }),
  "sla-early-warning": F({
    id: "sla-early-warning",
    name: "SLA Early-Warning",
    tagline: "Catch breaches before they happen.",
    layers: ["MCP Server", "Agentic RAG"],
    route: "POST /api/ai/sla-early-warning",
    what: "Surfaces the jobs approaching an SLA breach within the warning window and the recommended action for each.",
    how: "It computes time-to-breach from each open job's SLA due date and current status, then ARAG explains which to act on first and why.",
    why: "You intervene while there's still time to save the SLA, protecting penalty exposure and customer trust.",
    problem: "Standard alerts fire only once a threshold is already breached — by then it's a penalty, not a prevention.",
  }),
  triage: F({
    id: "triage",
    name: "Smart Intake Triage",
    tagline: "Turn a messy request into a structured job.",
    layers: ["Agentic RAG"],
    route: "POST /api/ai/triage",
    what: "Reads a free-text customer request and classifies it into job type, priority, required skills and a suggested SLA.",
    how: "ARAG interprets the request against your real skill set and job taxonomy and returns structured fields ready to create a work order.",
    why: "Intake is consistent and fast regardless of who takes the call, and urgent work is flagged urgent immediately.",
    problem: "Free-text requests get mis-triaged, under-prioritised or sent to someone without the right skills, causing call-backs and SLA misses.",
  }),
  "draft-quote": F({
    id: "draft-quote",
    name: "Site-Adaptive Quote Drafting",
    tagline: "A grounded quote draft from comparable jobs.",
    layers: ["Agentic RAG", "MCP Server", "Human-in-the-loop"],
    route: "POST /api/ai/draft-quote",
    what: "Drafts a quote for a work order — labour, materials, margin — anchored to what comparable completed jobs actually cost.",
    how: "It gathers comparable jobs of the same type, derives median labour rate/hours and material cost from their real costing, and drafts the quote. It refuses to guess when there aren't enough comparables. The draft is always reviewed by a human before it's sent.",
    why: "Faster, more consistent quoting that's grounded in your own history — not a finger in the air.",
    problem: "Quoting is slow and inconsistent; under time pressure jobs get under-priced (margin lost) or over-priced (deal lost).",
  }),
  "similar-work-orders": F({
    id: "similar-work-orders",
    name: "Duplicate / Callback Detection",
    tagline: "Spot repeat visits and warranty call-backs.",
    layers: ["Agentic RAG", "MCP Server"],
    route: "POST /api/ai/similar-work-orders",
    what: "Flags whether a job is a likely duplicate of an open job or a call-back to recently completed work at the same site.",
    how: "It gathers sibling jobs at the site and uses the model to judge semantic similarity of the issue, returning duplicates and call-backs with a confidence level.",
    why: "You avoid sending two crews to the same problem and you catch warranty call-backs that should be free — protecting margin and reputation.",
    problem: "Repeat issues and call-backs hide in the job list; without correlation you re-bill work that should be under warranty or double-dispatch.",
  }),
  "parts-kit": F({
    id: "parts-kit",
    name: "Parts-Kit Prediction",
    tagline: "Pack the right parts the first time.",
    layers: ["Agentic RAG", "MCP Server"],
    route: "POST /api/ai/parts-kit",
    what: "Suggests the parts a job is likely to need, learned from what comparable jobs actually consumed.",
    how: "It aggregates real stock consumption across comparable completed jobs of the same type and ranks parts by how often they're used and in what quantity.",
    why: "First-time-fix rates go up and second trips for a forgotten part go down — the single biggest hidden cost in field service.",
    problem: "Technicians arrive without the right part and have to return, doubling travel cost and delaying the customer.",
  }),
  "safety-preflight": F({
    id: "safety-preflight",
    name: "Safety Pre-Flight",
    tagline: "Controls for the job + a clearance check on the tech.",
    layers: ["Agentic RAG", "MCP Server"],
    route: "POST /api/ai/safety-preflight",
    what: "Assembles the safety controls and SWMS that apply to a job and checks the assigned technician holds the required clearances.",
    how: "ARAG retrieves the relevant safety policy/SWMS for the job type, while the ERP supplies the required skills and the assigned tech's held certifications — gaps are flagged.",
    why: "Safety is built into dispatch, not bolted on after an incident — and you don't send an uncleared worker to a high-risk task.",
    problem: "Safety controls live in documents nobody reads before a job, and clearance checks are manual and easily skipped under time pressure.",
  }),
  "site-access-briefing": F({
    id: "site-access-briefing",
    name: "Site-Access Briefing",
    tagline: "Everything the tech needs before they arrive.",
    layers: ["Agentic RAG", "MCP Server"],
    route: "POST /api/ai/site-access-briefing",
    what: "A short 'before you arrive' note: who to contact, access and parking, the preferred visit window, and on-site hazards like pets.",
    how: "It reads the site record and composes a concise briefing from only the fields that are populated — it never invents access details.",
    why: "Fewer failed visits and awkward arrivals; the tech turns up prepared and gets in first time.",
    problem: "Access details are scattered in site notes and often missed, causing wasted trips when nobody's there or the gate is locked.",
  }),
  "completion-note": F({
    id: "completion-note",
    name: "Completion Note",
    tagline: "A clean write-up of the work, drafted for you.",
    layers: ["Agentic RAG", "MCP Server", "Human-in-the-loop"],
    route: "POST /api/ai/completion-note",
    what: "Drafts a professional completion note for a finished job from the time logged, parts consumed and any field notes.",
    how: "It assembles the real time entries, stock consumed and notes for the job and has ARAG turn them into a tidy customer-ready summary, which the tech edits and approves.",
    why: "Technicians spend less time on paperwork and the customer record reads consistently, which helps disputes and warranty claims later.",
    problem: "Completion notes are rushed, inconsistent or skipped, leaving thin records that cause billing disputes and weak warranty evidence.",
  }),
  "work-order-timeline": F({
    id: "work-order-timeline",
    name: "Work-Order Timeline",
    tagline: "The job's whole story, narrated.",
    layers: ["Agentic RAG", "MCP Server"],
    route: "POST /api/ai/work-order-timeline",
    what: "A narrated chronology of a job — created, scheduled, time logged, quoted, invoiced — for handovers and disputes.",
    how: "It collects every dated event for the job from the ERP and orders them into a readable timeline with a short narrative.",
    why: "Anyone can pick up a job and instantly understand its history — no archaeology through screens before a customer call.",
    problem: "A job's history is scattered across modules; reconstructing 'what happened and when' for a dispute takes ages.",
  }),
  "time-anomaly": F({
    id: "time-anomaly",
    name: "Time Anomaly Check",
    tagline: "Flag jobs that took far longer than they should.",
    layers: ["Agentic RAG", "MCP Server"],
    route: "POST /api/ai/time-anomaly",
    what: "Flags a job whose logged hours are unusually high compared with similar jobs of the same type.",
    how: "It compares the job's logged hours against the typical hours for comparable jobs and flags it when it exceeds a statistical threshold, with the numbers shown.",
    why: "You catch productivity problems, training needs or time-sheet errors while they're still recoverable.",
    problem: "Labour over-runs are the quiet killer of margin and only show up — too late — in a month-end report, with no context.",
  }),
  "variation-claim": F({
    id: "variation-claim",
    name: "Variation / Additional-Works Claim",
    tagline: "Capture scope creep you'd otherwise eat.",
    layers: ["Agentic RAG", "MCP Server", "Human-in-the-loop"],
    route: "POST /api/ai/variation-claim",
    what: "Drafts a variation note when a job's actuals exceed the quote, so additional works can be billed instead of absorbed.",
    how: "It compares actual hours and cost against the quote, and when the variance is material, drafts a clear, customer-ready variation explanation for approval.",
    why: "Recovers revenue that's routinely lost to unbilled scope creep — straight to the bottom line.",
    problem: "Extra work gets done but never claimed because writing the variation is fiddly; the contractor silently absorbs the cost.",
  }),
  "customer-status-update": F({
    id: "customer-status-update",
    name: "Customer Status Update",
    tagline: "A polished progress note, ready to send.",
    layers: ["Agentic RAG", "MCP Server", "Human-in-the-loop"],
    route: "POST /api/ai/customer-status-update",
    what: "Drafts a friendly, accurate status update to the customer for a job, based on its current state.",
    how: "It reads the job's status, site and schedule and composes an on-brand update for a human to review and send.",
    why: "Proactive, consistent communication that reduces 'where's my job?' calls and lifts customer satisfaction.",
    problem: "Customers are left in the dark because writing updates is low-priority busywork, driving chase-up calls and poor reviews.",
  }),
  "fault-root-cause": F({
    id: "fault-root-cause",
    name: "Recurring-Fault Root Cause",
    tagline: "Why the same thing keeps breaking at a site.",
    layers: ["Agentic RAG", "MCP Server", "Human-in-the-loop"],
    route: "POST /api/ai/fault-root-cause",
    what: "Investigates a site's job history to rank the likely root causes of a recurring fault — workmanship, parts, call-back pattern — with the evidence behind each.",
    how: "It correlates repeat jobs at the site (same issue), call-back timing, labour over-runs and parts usage, retrieves any relevant SOP, and ranks causes by weight with citations. It can propose a follow-up job, which a human approves.",
    why: "You fix the actual cause instead of the same symptom over and over — ending the cycle of repeat visits.",
    problem: "Recurring faults are treated as one-off jobs because the pattern spans many work orders no single person connects.",
  }),
  "commit-date": F({
    id: "commit-date",
    name: "Service Commit-Date Co-Pilot",
    tagline: "Tell the customer a date you can keep.",
    layers: ["MCP Server", "Agentic RAG", "Human-in-the-loop"],
    route: "POST /api/ai/commit-date",
    what: "Works out the earliest realistic completion date for a job and names the binding constraint — parts on order, capacity — with an alternative.",
    how: "It predicts the parts the job needs, checks on-hand stock and any open purchase-order ETAs, factors in lead time, and has ARAG narrate the recommended date and how to beat it (e.g. expedite a PO).",
    why: "Front-line staff commit dates with confidence while the customer is still on the phone, instead of 'I'll call you back' — and they win more orders by being faster.",
    problem: "Promising a date means manually checking stock, POs and capacity; people guess, then miss the date or lose the job to a faster competitor.",
  }),
  playbook: F({
    id: "playbook",
    name: "Job Playbook",
    tagline: "Turn experience into a reusable, safe procedure.",
    layers: ["Agentic RAG", "Human-in-the-loop"],
    route: "POST /api/ai/playbook",
    what: "Generates a structured playbook for a job — steps, typical materials, required skills, estimated hours and safety controls — grounded in your history and safety docs.",
    how: "It first checks ARAG can actually ground the job in comparable work and safety documentation (refusing nonsense jobs), then assembles a structured procedure you can save as a reusable template.",
    why: "Best practice becomes repeatable and teachable instead of living only in your most experienced person's head.",
    problem: "Know-how walks out the door with senior staff; new techs reinvent the approach (and the mistakes) on every job.",
  }),
  "playbook-save": F({
    id: "playbook-save",
    name: "Save Playbook as Template",
    tagline: "Bank a good playbook back into the knowledge base.",
    layers: ["Agentic RAG", "Human-in-the-loop"],
    route: "POST /api/ai/playbook/save",
    what: "Saves an approved playbook back into the knowledge base as a reusable template that future answers and playbooks can draw on.",
    how: "The approved playbook is written into ARAG as a labelled 'playbook' document, so it becomes part of the grounded corpus the whole system retrieves from.",
    why: "The system gets smarter with use — your accumulated procedures compound instead of being regenerated from scratch.",
    problem: "Good procedures are produced once and lost; nothing captures and re-uses institutional knowledge.",
  }),
  "quote-risk": F({
    id: "quote-risk",
    name: "Quote Risk Check",
    tagline: "Catch under- and over-pricing before you send.",
    layers: ["Agentic RAG", "MCP Server"],
    route: "POST /api/ai/quote-risk",
    what: "Checks a quote's margin against comparable jobs and your margin floor, flagging if it's priced too low or out of line.",
    how: "It compares the quote's margin to the average of comparable quotes of the same type and to the configured margin-risk threshold, then explains the verdict.",
    why: "Protects margin on every quote and stops obvious mispricing leaving the building.",
    problem: "Margin leaks one quote at a time; without a comparison there's no signal that a quote is below where it should be.",
  }),
  "quote-comms": F({
    id: "quote-comms",
    name: "Quote Cover-Note & Follow-Up",
    tagline: "Professional quote emails, drafted instantly.",
    layers: ["Agentic RAG", "Human-in-the-loop"],
    route: "POST /api/ai/quote-comms",
    what: "Drafts the cover note that accompanies a quote, or a follow-up chaser if it's gone quiet.",
    how: "It reads the quote and account and composes an on-brand, ready-to-send message for a human to review.",
    why: "Quotes go out faster and get followed up consistently, which directly lifts win rates.",
    problem: "Quotes sit un-sent or un-chased because writing the email is friction; deals quietly expire.",
  }),
  "lost-quotes": F({
    id: "lost-quotes",
    name: "Lost-Quote Analysis",
    tagline: "Learn why you're losing work.",
    layers: ["Agentic RAG", "MCP Server"],
    route: "POST /api/ai/lost-quotes",
    what: "Analyses rejected and expired quotes for patterns — which job types, margins or accounts you lose most — so you can fix pricing or process.",
    how: "It gathers lost quotes, groups them by job type and margin, and has ARAG surface the patterns and likely reasons.",
    why: "Turns a pile of dead quotes into a pricing and sales-process improvement you can act on.",
    problem: "Lost quotes are forgotten, so the same losing pattern repeats quarter after quarter with no feedback loop.",
  }),
  "margin-insight": F({
    id: "margin-insight",
    name: "Margin Insight",
    tagline: "See exactly where margin leaks, by job type.",
    layers: ["Agentic RAG", "MCP Server"],
    route: "POST /api/ai/margin-insight",
    what: "Ranks job types by realised gross margin so you can see which work is actually making money and which is quietly losing it.",
    how: "It computes real margin from costing across recent completed jobs, aggregates by job type, and has ARAG explain the leakiest categories.",
    why: "Lets you re-price or stop doing unprofitable work — a direct lever on profitability.",
    problem: "Top-line revenue hides loss-making work; without per-type margin you keep selling the jobs that lose money.",
  }),
  "account-health": F({
    id: "account-health",
    name: "Account Health & Churn Risk",
    tagline: "Know which customers are slipping.",
    layers: ["Agentic RAG", "MCP Server"],
    route: "POST /api/ai/account-health",
    what: "Summarises an account's health — job volume, recency, quote rejection rate and overdue balance — and flags churn risk.",
    how: "It computes the account's metrics from the live ERP and has ARAG turn them into a plain-language health read.",
    why: "Account managers spot at-risk relationships early and act before the customer leaves.",
    problem: "Churn signals are spread across jobs, quotes and invoices; by the time anyone notices, the customer is already gone.",
  }),
  "proactive-maintenance": F({
    id: "proactive-maintenance",
    name: "Proactive Maintenance Suggestions",
    tagline: "Find the next job to offer a customer.",
    layers: ["Agentic RAG", "MCP Server"],
    route: "POST /api/ai/proactive-maintenance",
    what: "Suggests proactive maintenance services to offer an account, based on their job history and cadence.",
    how: "It analyses the account's recurring job types and timing and has ARAG propose relevant proactive offers.",
    why: "Converts reactive break-fix customers into recurring, planned revenue.",
    problem: "Upsell opportunities sit unseen in job history; nobody has time to mine each account for the next sensible offer.",
  }),
  "recurring-suggest": F({
    id: "recurring-suggest",
    name: "Recurring-Plan Suggestion",
    tagline: "Propose a maintenance contract from real cadence.",
    layers: ["Agentic RAG", "MCP Server"],
    route: "POST /api/ai/recurring-suggest",
    what: "Proposes a recurring maintenance plan for an account, inferred from how often they actually have recurring-type work.",
    how: "It detects the cadence of maintenance/inspection jobs in the account's history and has ARAG propose a sensible plan (e.g. quarterly).",
    why: "Locks in predictable, recurring revenue and improves customer outcomes through planned upkeep.",
    problem: "Recurring work is booked ad-hoc, leaving revenue unpredictable and assets under-maintained between reactive calls.",
  }),
  "recurring-preview": F({
    id: "recurring-preview",
    name: "Recurring-Run Preview",
    tagline: "See what the next recurring run will create.",
    layers: ["MCP Server", "Agentic RAG"],
    route: "POST /api/ai/recurring-preview",
    what: "Previews the jobs the next recurring-maintenance run would generate, and spots where multiple plans hit the same site so visits can be batched.",
    how: "It reads the active recurring plans that are due, lists what they'd create, and has ARAG flag batching opportunities (same site, same window).",
    why: "You confirm the run before it floods the board, and you save trips by combining visits to the same site.",
    problem: "Recurring runs create work blindly; without a preview you over-dispatch and miss obvious chances to batch nearby jobs.",
  }),
  "risk-watchlist": F({
    id: "risk-watchlist",
    name: "Account Risk Watchlist",
    tagline: "One ranked list of who's about to be a problem.",
    layers: ["MCP Server", "Agentic RAG"],
    route: "POST /api/ai/risk-watchlist",
    what: "A composite, multi-factor risk score per account — SLA-risk jobs, open work and overdue cash combined — ranked highest-risk first.",
    how: "It computes each factor from the live ERP, blends them into a weighted score, and ranks accounts so the most exposed surface at the top, with the contributing factors shown.",
    why: "Leaders see the handful of accounts that need attention this week without reading five separate reports.",
    problem: "Risk that's obvious in combination is invisible factor-by-factor; no single threshold-based report surfaces 'this account is bad on three fronts at once.'",
  }),
  "dunning-draft": F({
    id: "dunning-draft",
    name: "Dunning / Payment Reminder",
    tagline: "Get paid faster with the right-toned reminder.",
    layers: ["Agentic RAG", "MCP Server", "Human-in-the-loop"],
    route: "POST /api/ai/dunning-draft",
    what: "Drafts an overdue-invoice reminder whose tone matches how late the invoice is — gentle nudge through to final notice.",
    how: "It reads the invoice and how many days overdue it is, selects the appropriate tone, and drafts a ready-to-send reminder for approval.",
    why: "Improves cash collection without souring relationships — and removes the awkwardness that delays chasing.",
    problem: "Overdue invoices go unchased because writing the reminder is uncomfortable and time-consuming, hurting cash flow.",
  }),
  "finance-exceptions": F({
    id: "finance-exceptions",
    name: "Finance Exceptions",
    tagline: "Explain and fix AP/AR exceptions, grouped by cause.",
    layers: ["MCP Server", "Agentic RAG", "Human-in-the-loop"],
    route: "POST /api/ai/finance-exceptions",
    what: "Scans supplier bills and customer invoices for exceptions — 3-way-match breaks, missing PO links, disputed bills, overdue items, missing dates — explains each in plain language with the governing policy, and groups them by root cause for one-click batch fixes.",
    how: "A deterministic scan computes the exceptions from the live finance data; Agentic RAG retrieves the relevant finance-policy passage to cite; fixes are applied through the ERP only after a human approves, and every change is audit-logged.",
    why: "Turns hours of period-end detective work into an exception review — and stops staff posting bad workarounds under deadline pressure.",
    problem: "Posting errors and mismatches are cryptic and scattered; resolving each one means hunting across modules and policy documents, and audit findings follow.",
  }),
  "cost-exceptions": F({
    id: "cost-exceptions",
    name: "Cost-Variance Exceptions",
    tagline: "Completed jobs that lost money, pre-labelled.",
    layers: ["MCP Server", "Agentic RAG"],
    route: "POST /api/ai/cost-exceptions",
    what: "Reviews recent completed jobs and pre-labels each cost variance as Explained, Partial or Unresolved, so you only investigate the ones that matter.",
    how: "It computes margin and variance-from-quote from real costing for each completed job and classifies them, surfacing the unresolved ones first.",
    why: "Your accountant spends time deciding, not investigating — and margin leaks get caught while they're still actionable.",
    problem: "A WIP report shows a variance but not why; tracing each one manually across costing, time and procurement consumes the whole reporting week.",
  }),
  "demand-reorder": F({
    id: "demand-reorder",
    name: "Demand-Aware Reorder",
    tagline: "Reorder weighted by the jobs actually coming up.",
    layers: ["MCP Server", "Agentic RAG"],
    route: "POST /api/ai/demand-reorder",
    what: "Recommends what to reorder, weighting low-stock items by the demand from jobs scheduled in the near term.",
    how: "It finds items below reorder point and cross-references upcoming scheduled work to prioritise what you'll actually need, then ARAG explains the list.",
    why: "You avoid both stock-outs that stall jobs and cash tied up in stock you don't need yet.",
    problem: "Static reorder points ignore the forward job book, so you run out of the parts the next jobs need while over-stocking others.",
  }),
  lots: F({
    id: "lots",
    name: "Traceable Lots",
    tagline: "The lots you can trace through jobs.",
    layers: ["MCP Server"],
    route: "POST /api/ai/lots",
    what: "Lists the part lots that have moved through the business (received and consumed on jobs) so you can pick one to trace.",
    how: "A deterministic query over stock movements aggregates the lot identifiers and how many jobs each was consumed on.",
    why: "Gives you the starting point for an instant recall trace — no spreadsheet hunting.",
    problem: "Lot information is buried in stock-movement records and effectively unusable when you need it under pressure.",
  }),
  "lot-trace": F({
    id: "lot-trace",
    name: "Part / Lot Trace",
    tagline: "Recall-ready: where a lot came from and went.",
    layers: ["MCP Server"],
    route: "POST /api/ai/lot-trace",
    what: "Traces a part lot both backward (where it was received) and forward (which jobs, sites and customers it was used on) — the recall trace, in one click.",
    how: "A deterministic query follows the lot through receipt and consumption stock movements, joining out to the jobs and accounts that received it.",
    why: "If a batch is faulty or recalled, you know exactly who's affected in seconds — protecting customers and limiting liability.",
    problem: "Forward-and-backward traceability normally means running two manual processes and reconciling records by hand, which takes hours you don't have in a recall.",
  }),
  "fleet-compliance": F({
    id: "fleet-compliance",
    name: "Fleet Compliance Watchdog",
    tagline: "No vehicle off the road for a missed service.",
    layers: ["MCP Server", "Agentic RAG"],
    route: "POST /api/ai/fleet-compliance",
    what: "Surfaces vehicles with a service or registration due soon, so nothing lapses.",
    how: "It checks each active vehicle's service and registration due dates against a warning window and has ARAG summarise what's due.",
    why: "Keeps the fleet legal and on the road, avoiding fines and the disruption of an un-registered or un-serviced vehicle.",
    problem: "Service and rego dates live in a spreadsheet nobody watches; a lapse is discovered only when a vehicle is pulled over or breaks down.",
  }),
  "asset-service": F({
    id: "asset-service",
    name: "Fleet / Asset Service Co-Pilot",
    tagline: "Diagnose a symptom, cite the manual, propose a fix.",
    layers: ["Agentic RAG", "MCP Server", "Human-in-the-loop"],
    route: "POST /api/ai/asset-service",
    what: "Takes a vehicle or asset and a reported symptom and returns grounded maintenance guidance, citing the care notes, plus its service-due status.",
    how: "It reads the asset's details and due dates from the ERP and retrieves the relevant equipment manual via ARAG to ground its advice; it can propose a service job for approval.",
    why: "Front-line staff get expert maintenance guidance without an expert on hand, and small issues are caught before they become breakdowns.",
    problem: "Equipment knowledge is locked in manuals nobody reads, so symptoms are ignored until the asset fails.",
  }),
  "skill-gap": F({
    id: "skill-gap",
    name: "Skill-Coverage Gaps",
    tagline: "Find your single points of failure.",
    layers: ["MCP Server", "Agentic RAG"],
    route: "POST /api/ai/skill-gap",
    what: "Identifies skills that open jobs require but too few active staff hold — your single points of failure.",
    how: "It joins the skills required by open jobs against the skills held by active employees and flags any required skill with one or zero holders.",
    why: "Workforce and training decisions are driven by real demand, and you de-risk before a key person is on leave.",
    problem: "A capability gap is invisible until the one person who can do the job is unavailable and the work stalls.",
  }),
  "exec-summary": F({
    id: "exec-summary",
    name: "Executive Summary",
    tagline: "A board-ready monthly read in one paragraph.",
    layers: ["Agentic RAG", "MCP Server"],
    route: "POST /api/ai/exec-summary",
    what: "A concise, board-ready summary of the month — revenue, outstanding receivables, margin and operational risk — in plain English.",
    how: "It gathers the real KPIs from across the operation and has ARAG narrate them into an executive brief.",
    why: "Leadership gets the story behind the numbers without waiting on a finance pack.",
    problem: "Pulling a coherent monthly narrative together is a manual, multi-source chore that's always late and always slightly different.",
  }),
  "audit-assistant": F({
    id: "audit-assistant",
    name: "Audit Assistant",
    tagline: "Ask the audit log in plain English.",
    layers: ["Agentic RAG", "MCP Server"],
    route: "POST /api/ai/audit-assistant",
    what: "Answers natural-language questions about the audit log — who changed what, when — citing the entries.",
    how: "It loads the recent audit entries and has ARAG answer strictly from them, summarising or pinpointing as the question requires.",
    why: "Compliance and incident questions are answered in seconds instead of scrolling raw logs.",
    problem: "Audit trails are complete but unreadable; answering 'who approved this and when' means manual log archaeology.",
  }),
  "compliance-readiness": F({
    id: "compliance-readiness",
    name: "Compliance Readiness",
    tagline: "Compare written policy to what's actually happening.",
    layers: ["Agentic RAG", "MCP Server"],
    route: "POST /api/ai/compliance-readiness",
    what: "Produces a readiness assessment that compares your written policy against the live configuration and data, flagging policy-vs-practice gaps.",
    how: "It pulls live settings and recent records from the ERP, retrieves the written policy via ARAG, and has the model surface where practice diverges from policy.",
    why: "You find and fix gaps before an auditor or examiner does — turning compliance from a scramble into a continuous check.",
    problem: "Written policy and actual system behaviour drift apart and the gap is only discovered, embarrassingly, during an audit.",
  }),
  "extract-document": F({
    id: "extract-document",
    name: "Document Import (Visual LLM)",
    tagline: "Read a supplier invoice into a structured draft.",
    layers: ["Visual LLM", "MCP Server", "Human-in-the-loop"],
    route: "POST /api/ai/extract-document",
    what: "Reads an uploaded supplier invoice or PO document and produces a structured draft bill — supplier matched, line items matched to SKUs, and the referenced PO linked for a 3-way match.",
    how: "ARAG's document ingestion performs OCR, then the model structures the text into fields. It fuzzy-matches the supplier and SKUs against your data and links the PO. The result is a draft a human reviews before it's created.",
    why: "Eliminates manual data entry from paper/PDF invoices and catches mismatches at capture time, not at month-end.",
    problem: "Supplier documents are re-keyed by hand — slow and error-prone — and posting errors surface far too late.",
  }),
};

export const AI_FEATURE_COUNT = Object.keys(AI_FEATURES).length;
